[tool.poetry]
name = "cp-badges"
version = "0.1.0"
description = "Competitive Programming badges"
authors = ["Joonhyung Shin <joonhyung.shin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.1.2"
gunicorn = "^20.1.0"
Flask-Caching = "^1.11.1"
pybadges = "^3.0.0"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
