[tool.poetry]
name = "cp-badges"
version = "0.1.0"
description = "Competitive programming badges"
authors = ["Joonhyung Shin <joonhyung.shin@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cp_badges"}]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.2.2"
gunicorn = "^20.1.0"
Flask-Caching = "^2.0.1"
pybadges = "^3.0.0"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
